function out = mcEmptyTrodeStructure

        out = struct(...
            'name', '',...
            'channels', [],...
            'cluster', [],...
            'spikes', [],...
            'splitMergeToolHandle', [],...
            'display', 0 ...
            );