function out = mcEmptyChannelStruct
    global state
    
        out = struct(...
            'Name', '', ...
            'SampleRate', state.mcViewer.sampleRate, ... %all channels from PCI 6259 board should be at same sample rate
            'mcFigureInclude', 0, ...
            'auxFigureInclude', 0, ...
            'ShowFilter', 0, ...
            'LowPass', 0, ...
            'HighPass', 0 ...
        );