function mcUpdateRespirationLines

    global state
    
    if isempty(state.mcViewer.features) || isempty(state.mcViewer.features.respiration)
        return
    end
    nDisplayChannels = length(state.mcViewer.displayedChannels);
    
    for i = 1:nDisplayChannels
        if state.mcViewer.showRespiration
            if isempty(state.mcViewer.features.respiration.times{1, state.mcViewer.fileCounter})
                disp('error in mcUpdateRespirationLines')
                return
            end
            if state.mcViewer.displayedChannels(1, i) == state.mcViewer.respirationChannel  % actually mark the peaks if this is the respiration channel
                Indices = state.mcViewer.features.respiration.indices{1, state.mcViewer.fileCounter};
                respYData = state.mcViewer.displayData(Indices, state.mcViewer.respirationChannel);
                IndicesShifted = state.mcViewer.features.respiration.indicesShifted{1, state.mcViewer.fileCounter};
                respYDataShifted = state.mcViewer.displayData(IndicesShifted, state.mcViewer.respirationChannel);                
            else
                respYData = state.mcViewer.features.respiration.indices{1, state.mcViewer.fileCounter} .* 0;
                respYDataShifted = state.mcViewer.features.respiration.indicesShifted{1, state.mcViewer.fileCounter} .* 0;                
            end
                
%% unshifted times                
            if ishandle(state.mcViewer.respirationLines(1, i))
                set(state.mcViewer.respirationLines(1, i),...
                    'Parent', state.mcViewer.axes(i),...
                    'XData', state.mcViewer.features.respiration.times{1, state.mcViewer.fileCounter},...
                    'YData', respYData,... % have marks be at y = 0
                    'Visible', 'on'...
                    );
            else
                state.mcViewer.respirationLines(1, i) = line(...
                    state.mcViewer.features.respiration.times{1, state.mcViewer.fileCounter},...
                    respYData,...
                    'LineStyle', 'none',...
                    'Marker', 'o',...
                    'MarkerSize', 5,...
                    'MarkerEdgeColor', 'g',...
                    'MarkerFaceColor', 'm',...
                    'Parent', state.mcViewer.axes(i),...
                    'Visible', 'on'...
                    );
            end
%% shifted times                
            if ishandle(state.mcViewer.respirationLinesShifted(1, i))
                set(state.mcViewer.respirationLinesShifted(1, i),...
                    'Parent', state.mcViewer.axes(i),...
                    'XData', state.mcViewer.features.respiration.timesShifted{1, state.mcViewer.fileCounter},...
                    'YData', respYDataShifted,... % have marks be at y = 0
                    'Visible', 'on'...
                    );
            else
                state.mcViewer.respirationLinesShifted(1, i) = line(...
                    state.mcViewer.features.respiration.timesShifted{1, state.mcViewer.fileCounter},...
                    respYDataShifted,...
                    'LineStyle', 'none',...
                    'Marker', '*',... 
                    'MarkerSize', 4,...
                    'MarkerEdgeColor', 'm',...
                    'MarkerFaceColor', 'g',...
                    'Parent', state.mcViewer.axes(i),...
                    'Visible', 'on'...
                    );
            end
        else
            if ishandle(state.mcViewer.respirationLines(1, i))
                set(state.mcViewer.respirationLines(1, i), 'Visible', 'off');
            end
            if ishandle(state.mcViewer.respirationLinesShifted(1, i))
                set(state.mcViewer.respirationLinesShifted(1, i), 'Visible', 'off');
            end       
        end
    end
        
       